source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'sinatra-cross_origin'
# gem 'fhir_client', :path => '../fhir_client'
gem 'fhir_client', :git => 'https://github.com/fhir-crucible/fhir_client.git', :branch => 'profiling'
# gem 'fhir_models', :path => '../fhir_models'
gem 'fhir_models', :git => 'https://github.com/fhir-crucible/fhir_models.git', :branch => 'profiling'
gem 'rest-client'
#gem 'fhir_scorecard'
# gem 'fhir_scorecard', :path => '../fhir_scorecard'
gem 'fhir_scorecard', :git => 'https://github.com/fhir-crucible/fhir_scorecard.git', :branch => 'profile_validations'
